### PR TITLE
Expose before/after_change_gcode

### PR DESCRIPTION
**Pull request by TheSin-**
Expose `before_change_gcode` and `after_change_gcode` to allow for user macros.

Example and use in https://github.com/viesturz/tapchanger/pull/25

### CODE REVIEW

**Comment by BrewNinja** [comment]
Any movement on this?

**Comment by viesturz** [comment]
Finally getting back to this. Let me try yo understand the use case a bit better first, following up in the other PR.

**Comment by TheSin-** [comment]
It’s okay I started my own fork, i was trying to avoid it be at the rate of commits I had too much of a back log of features, requests and enhancements

**Comment by viesturz** [comment]
Can you share the fork?

**Comment by TheSin-** [comment]
sure it's in the StealthChanger repo, but it's not fit for release yet lots of checks and balances missing ATM, I'm just trying to slowly move through it.

That being said if you are willing to work on these with me I'd MUCH rather not fork, it's confusing for users, but I need to be able to get PRs in a bit quicker (that being said I truly appreciate your review of it and working together we can move it forward quicker).

https://github.com/Stealthchanger/klipper-toolchanger

**Comment by viesturz** [comment]
Was pretty much out the whole Q1, normally I'm quite responsive.
That being said, I'm looking to keep the toolchanger core minimalistic, so depending what you are looking to do, it might be easier to keep things separate with occasional pull requests.

For this PR speficially, it's not clear how the new fields would be used. Right now it's just dead code.

**Comment by viesturz** [comment]
I reorganized the examples folder, if you are interested to add a Stealthchanger example there.

**Comment by viesturz** [comment]
Hi, pushed https://github.com/viesturz/klipper-toolchanger/commit/3bfc95b5ede49d6101234ee741f55b824f447506 to address this.

**Pull request closed without merging**
