### PR TITLE
addition of query commands for all probes

### PR DESCRIPTION
**Pull request by Contomo**
small quality of life things
uhh, havent checked to see if it works with cascading toolchangers yet.

### CODE REVIEW

**Comment by viesturz** [comment]
Thanks, generally looking good. 

Can you please update the command names to be a bit more consisatnt:
QUERY_PROBES -> QUERY_ALL_PROBES
QUERY_PROBE_TOOL_CALIBRATE -> TOOL_CALIBRATE_QUERY_PROBE (to have all commands prefixed with the TOOL_CALIBRATE_)

**Comment by Contomo** [comment]
QUERY_PROBE_TOOL_CALIBRATE -> TOOL_CALIBRATE_QUERY_PROBE makes sense, i wasnt certain on which way to name them since the other one is called QUERY_PROBE, and hitting tab would make the option of tool calibrate show up, but i guess it makes sense from the plugin standpoint (all indexed on tool_calibrate_).

QUERY_ALL_PROBES could be misleading since it doesnt contain the calibration probe, neither does it contain user setup extra Z probes or similar, QUERY_PROBE_ALL_TOOLS, QUERY_PROBE_ALL, or similar may be better (not sure if its good to stick with the common naming of klipper macros to make it easy to locate them.)

ill make the changes for now to the descriptions and names, you can also edit this pull request btw and name them how you prefer ^^

**Comment by VIN-y** [comment]
hey guys. it is not urgent, but can we push this commit through. The ability to query the calibration probe is actually pretty important for a floating probe setup.

**Comment by viesturz** [comment]
LGTM from me.
If you can rebase, the conflicts should be straightforward.

**Comment by Contomo** [comment]
what are you using for github stuff? im trying vscode currently... and im not really getting it. either because of github or vscode..

**Comment by VIN-y** [comment]
I use the GitHub Desktop app to sync my branch of the project to my PC. Then I have a separate folder, which I do all of my work in, using VSCode of equivalent like VSCodium. When the work is done, I will first go to the GitHub website to sync with the latest of main branch (I think it can be done in the app, but I have never tried it). Then, copy-paste the relevant files from the work folder to the synced folder. Then do the usual commit.

**Pull request merged**
